import mongoose from "mongoose";

const orderItemSchema = new mongoose.Schema({
    //we will store  productid instead of full product, productId is generated by mongoDB, later by using this id we can ref to that product easily.
  productId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: "Product",
  },
  quantity: {
    type: Number,
    required: true,
  },
});

const orderSchema = new mongoose.Schema(
  {
    orderPrice: {
      type: Number,
      required: true,
    },
    orderby: {
      type: mongoose.Schema.Types.ObjectId, //relationship #1
      ref: "User",
    },
    //orderitem means which "product" with how much "quantity" is being ordered
    orderItems:[orderItemSchema], //adding sub-schema "orderItemSchema" 
    address: {
        type: String,
        required: true,
      },
    status:{
        type: String,
        enum: ["PENDING","DELIVERED","CANCELLED"],
        default: "PENDING"
    }
  },
  { timestamps: true }
);

export const Order = mongoose.model("Order", orderSchema);
